---
title: "Table_development_LGH"
author: "Yoshito Kawakatsu"
date: "January 12, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) #Remove all
library(dplyr)
library(ggplot2)
library(readxl)
library(tidyverse)
library(kableExtra)
```

# Table for users
```{r}
lic <- read_xlsx("LGH Costing_20200422.xlsx", sheet = "LIC Input")
lmic <- read_xlsx("LGH Costing_20200422.xlsx", sheet = "LMIC Input")


# Unit cost adjustment
cpi <- read.csv("CPI_WB_2018_added.csv") #Revised
regional_inflation <- read_xls("Regional_inflation_20200212.xls", sheet = "Data")
class <- read_xls("CLASS_re.xls")

#------Function
tradable_conversion <- function(unit_cost, tradable_ratio, currency, global_inflation, exchange){
  if(currency == "USD") {
    unit_cost*tradable_ratio*global_inflation} else {
      ((unit_cost*tradable_ratio)/exchange)*global_inflation
    }
}


nontradable_conversion <- function(unit_cost,tradable_ratio, currency, cpi_adjust, exchange,country, exchange_end, gni, gni_selected_country){
  if(currency == "USD" & (country == "LIC" | country == "LMIC")) {
    unit_cost*(1-tradable_ratio)*cpi_adjust
  } else if (currency == "USD" & (country != "LIC" & country != "LMIC")){
    ((unit_cost*exchange)*(1-tradable_ratio))*cpi_adjust/exchange_end*(gni_selected_country/gni)} else {
      ((unit_cost*(1-tradable_ratio)*cpi_adjust)/exchange_end)*(gni_selected_country/gni)
    }
}
#--------------------

exchange <- read_xlsx("Exchange_rate.xlsx")
regional_inflation[,c(5:64)] <- (regional_inflation[,c(5:64)]/100)+1

all_tradable <- read_xlsx("alltradeable.xlsx")
all_nontradable <- read_xlsx("Nontradeable.xlsx")

#--------------------
```


```{r}
GNI <- read.csv("GNI_WB_USD_atlas_add3.csv")


GNI[GNI$Country == "LIC", c("X2015")] <- 794.4947062
GNI[GNI$Country == "LMIC", c("2015")] <- 2211.473603
```


#LIC
```{r}
###Select LIC
df <- lic
df <- df %>% 
  filter(`Original Unit Cost` != "NA")

gni_selected_country <- as.numeric(GNI[GNI$Country == "LIC", c("X2015")])

###

i <- 1
c <- 1
n <- 1

final_UC <- data.frame( Name = character(),
                        unit_cost = numeric(),
                        stringsAsFactors=FALSE)


#setting######################
#Setting
tradable_ratio <- 0.3
UC_Years <- 2016  # The output year
ancillary_HF_cost <- 0.5
above_HF <- 0.17
#setting end######################



#Adjusted UC------------------------------------------
# Adjustment database
    no <- nrow(df)
    adjustment <- data.frame(ID = 1:no, exchange = NA, country = NA, year = NA, n = NA, 
                                cpi_study = NA, cpi_end = NA, cpi_adjust = NA,
                                global_inflation = NA,
                                exchange_end = NA, gni = NA)

    
    for (i in 1:no){
      #Country
      country <- as.character(df[i,"Country"])
      adjustment[i,"country"] <- country
      
      #Original UC_Year
      year <- df[i,"Year"]
      adjustment[i,"year"] <- year
      
      #Output year
      n <- as.numeric(year) - 1960 +2
      end_year <- as.numeric(UC_Years - 1960 +2)
      
      # Exchange of original UC
      adjustment[i,"n"] <- n
      rate <- exchange[exchange$Country == country, n]
      adjustment[i,"exchange"] <- as.numeric(rate)
      
      # consumer price index
      cpi_year <- as.numeric(year) - 1960 + 6
      cpi_end_year <- as.numeric(UC_Years - 1960 +6)

      adjustment[i,"cpi_study"] <- as.numeric(cpi[cpi$Country == country, cpi_year])
      adjustment[i,"cpi_end"] <- as.numeric(cpi[cpi$Country == country, cpi_end_year])
      
      # Global inflation calculation
      col_n <- as.numeric(year) - 1960 + 5
      col_end <- as.numeric(UC_Years - 1960 +5)
      
      #Global inflation of 2016, 2017 or 2018
      adjustment[i,"global_inflation"] <-
        as.numeric(prod(as.matrix(regional_inflation[regional_inflation$Country == "World", col_n:col_end])))
      
      # Exchange rate of 2016, 2017 or 2018
      adjustment[i,"exchange_end"] <- as.numeric(exchange[exchange$Country == country, end_year])
      
      #GNI
      GNI_year <- UC_Years - 1990 +5
      adjustment[i,"gni"] <- as.numeric(GNI[GNI$Country == country, c("X2015")])
    }
    
    # GNI adjustment
    # GNI selected country = LIC or LMIC
    adjustment$gni_selected_country <- gni_selected_country
    adjustment$gni_adjust <- adjustment$gni_selected_country/ adjustment$gni
    
    # CPI adjustment rate
    adjustment[,"cpi_adjust"] <- adjustment$cpi_end / adjustment$cpi_study
    
    # Merge adjustments with uc
    ucm <- cbind(df, adjustment)
    
    # Tradable
    ucm$tradable_uc <- NA
    for (i in 1:no){
        ucm$tradable_uc[i] <- tradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               global_inflation = ucm$global_inflation[i],
                               exchange = ucm$exchange[i])
                    }
    
    
     for (i in 1:no){
      ucm$nontradable_uc[i] <- nontradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               cpi_adjust = ucm$cpi_adjust[i],
                               country = ucm$country[i],
                               exchange = ucm$exchange[i],
                               exchange_end = ucm$exchange_end[i],
                               gni = ucm$gni[i],
                               gni_selected_country = ucm$gni_selected_country[i])
                    }
    
    # Add ancillary + above HF costs
     ucm$adjusted_uc <- (ucm$tradable_uc + ucm$nontradable_uc)

     ###
     #Change all tradable and non-tradable
     


     
     for (i in 1:nrow(ucm)){
       if(ucm$Code[i] %in% all_tradable$Code & !(ucm$Code[i] %in% all_nontradable$Code)) {
         tradable_ratio <- 1.0
         ucm$adjusted_uc[i] <- tradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               global_inflation = ucm$global_inflation[i],
                               exchange = ucm$exchange[i])
         ucm$nontradable_uc[i] <- 0
         ucm$tradable_uc[i] <- tradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               global_inflation = ucm$global_inflation[i],
                               exchange = ucm$exchange[i])
         
       } else if (!(ucm$Code[i] %in% all_tradable$Code) & ucm$Code[i] %in% all_nontradable$Code) {
         tradable_ratio <- 0
         ucm$nontradable_uc[i] <- nontradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               cpi_adjust = ucm$cpi_adjust[i],
                               country = ucm$country[i],
                               exchange = ucm$exchange[i],
                               exchange_end = ucm$exchange_end[i],
                               gni = ucm$gni[i],
                               gni_selected_country = ucm$gni_selected_country[i])
         ucm$tradable_uc[i] <- 0
         ucm$adjusted_uc[i] <- nontradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               cpi_adjust = ucm$cpi_adjust[i],
                               country = ucm$country[i],
                               exchange = ucm$exchange[i],
                               exchange_end = ucm$exchange_end[i],
                               gni = ucm$gni[i],
                               gni_selected_country = ucm$gni_selected_country[i])
       }  else{
         ucm$adjusted_uc[i] <- ucm$adjusted_uc[i]
       }
     }
       

     
     
     ###
     
     ucm_lic <- ucm
     
         write.csv(ucm_lic, "Unit_cost_LIC_all_0422.csv")
         
      ucm_lic$Include <- ifelse(ucm_lic$HPP == 1, TRUE, FALSE)
         
        write.csv(ucm_lic[,c("Code","Intervention","HPP", "Include","Platform", "Urgency","Objective","PIN", "Coverage", "adjusted_uc")], "Unit_cost_LIC_select_0422.csv")

     
     lic_df <- ucm_lic %>% 
       select(Code, Platform, Urgency, Objective, HPP ,Intervention, adjusted_uc, PIN, Coverage, `Target Coverage`)
     
     lic_df <- lic_df %>% 
       rename("LIC.Unit.Price" = adjusted_uc,
              "LIC.PIN" = PIN,
              "LIC.Coverage" = Coverage,
              "LIC.Target" = `Target Coverage`)
     
     
     write.csv(lic_df, "Unit_cost_LIC_0422.csv")
```


# LMIC
```{r}
###Select LMIC
df <- lmic
df <- df %>% 
  filter(`Original Unit Cost` != "NA")

gni_selected_country <- as.numeric(GNI[GNI$Country == "LMIC", c("X2015")])

###

i <- 1
c <- 1
n <- 1

final_UC <- data.frame( Name = character(),
                        unit_cost = numeric(),
                        stringsAsFactors=FALSE)


#setting######################
#Setting
tradable_ratio <- 0.3
UC_Years <- 2016  # The output year
ancillary_HF_cost <- 0.5
above_HF <- 0.17
#setting end######################



#Adjusted UC------------------------------------------
# Adjustment database
    no <- nrow(df)
    adjustment <- data.frame(ID = 1:no, exchange = NA, country = NA, year = NA, n = NA, 
                                cpi_study = NA, cpi_end = NA, cpi_adjust = NA,
                                global_inflation = NA,
                                exchange_end = NA, gni = NA)

    
    for (i in 1:no){
      #Country
      country <- as.character(df[i,"Country"])
      adjustment[i,"country"] <- country
      
      #Original UC_Year
      year <- df[i,"Year"]
      adjustment[i,"year"] <- year
      
      #Output year
      n <- as.numeric(year) - 1960 +2
      end_year <- as.numeric(UC_Years - 1960 +2)
      
      # Exchange of original UC
      adjustment[i,"n"] <- n
      rate <- exchange[exchange$Country == country, n]
      adjustment[i,"exchange"] <- as.numeric(rate)
      
      # consumer price index
      cpi_year <- as.numeric(year) - 1960 + 6
      cpi_end_year <- as.numeric(UC_Years - 1960 +6)

      adjustment[i,"cpi_study"] <- as.numeric(cpi[cpi$Country == country, cpi_year])
      adjustment[i,"cpi_end"] <- as.numeric(cpi[cpi$Country == country, cpi_end_year])
      
      # Global inflation calculation
      col_n <- as.numeric(year) - 1960 + 5
      col_end <- as.numeric(UC_Years - 1960 +5)
      
      #Global inflation of 2016, 2017 or 2018
      adjustment[i,"global_inflation"] <-
        as.numeric(prod(as.matrix(regional_inflation[regional_inflation$Country == "World", col_n:col_end])))
      
      # Exchange rate of 2016, 2017 or 2018
      adjustment[i,"exchange_end"] <- as.numeric(exchange[exchange$Country == country, end_year])
      
      #GNI
      GNI_year <- UC_Years - 1990 +5
      adjustment[i,"gni"] <- as.numeric(GNI[GNI$Country == country, c("X2015")])
    }
    
    # GNI adjustment
    # GNI selected country = LIC or LMIC
    adjustment$gni_selected_country <- gni_selected_country
    adjustment$gni_adjust <- adjustment$gni_selected_country/ adjustment$gni
    
    # CPI adjustment rate
    adjustment[,"cpi_adjust"] <- adjustment$cpi_end / adjustment$cpi_study
    
    # Merge adjustments with uc
    ucm <- cbind(df, adjustment)
    
    # Tradable
    ucm$tradable_uc <- NA
    for (i in 1:no){
        ucm$tradable_uc[i] <- tradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               global_inflation = ucm$global_inflation[i],
                               exchange = ucm$exchange[i])
                    }
    
    
     for (i in 1:no){
      ucm$nontradable_uc[i] <- nontradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               cpi_adjust = ucm$cpi_adjust[i],
                               exchange = ucm$exchange[i],
                               country = ucm$country[i],
                               exchange_end = ucm$exchange_end[i],
                               gni = ucm$gni[i],
                               gni_selected_country = ucm$gni_selected_country[i])
                    }
    
    # Add ancillary + above HF costs
     ucm$adjusted_uc <- (ucm$tradable_uc + ucm$nontradable_uc)

    # Change tradable ratio

     for (i in 1:nrow(ucm)){
       if(ucm$Code[i] %in% all_tradable$Code & !(ucm$Code[i] %in% all_nontradable$Code)) {
         tradable_ratio <- 1.0
         ucm$adjusted_uc[i] <- tradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               global_inflation = ucm$global_inflation[i],
                               exchange = ucm$exchange[i])
         ucm$nontradable_uc[i] <- 0
         ucm$tradable_uc[i] <- tradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               global_inflation = ucm$global_inflation[i],
                               exchange = ucm$exchange[i])
         
       } else if (!(ucm$Code[i] %in% all_tradable$Code) & ucm$Code[i] %in% all_nontradable$Code) {
         tradable_ratio <- 0
         ucm$nontradable_uc[i] <- nontradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               cpi_adjust = ucm$cpi_adjust[i],
                               country = ucm$country[i],
                               exchange = ucm$exchange[i],
                               exchange_end = ucm$exchange_end[i],
                               gni = ucm$gni[i],
                               gni_selected_country = ucm$gni_selected_country[i])
         ucm$tradable_uc[i] <- 0
         ucm$adjusted_uc[i] <- nontradable_conversion(
                               unit_cost = as.numeric(ucm$`Original Unit Cost`[i]),
                               tradable_ratio = tradable_ratio,
                               currency = ucm$`Original Currency`[i],
                               cpi_adjust = ucm$cpi_adjust[i],
                               country = ucm$country[i],
                               exchange = ucm$exchange[i],
                               exchange_end = ucm$exchange_end[i],
                               gni = ucm$gni[i],
                               gni_selected_country = ucm$gni_selected_country[i])
       }  else{
         ucm$adjusted_uc[i] <- ucm$adjusted_uc[i]
       }
     }
    
     
     
     
     
     ucm_lmic <- ucm
     
    write.csv(ucm_lmic, "Unit_cost_LMIC_all_0422.csv")
    
    
    ucm_lmic$Include <- ifelse(ucm_lmic$HPP == 1, TRUE, FALSE)

    
    write.csv(ucm_lmic[,c("Code","Intervention", "HPP","Include","Platform", "Urgency","Objective","PIN", "Coverage", "adjusted_uc")], "Unit_cost_LMIC_select_0422.csv")
    
     
     lmic_df <- ucm_lmic %>% 
       select(Code, Platform, Urgency, Objective, HPP ,Intervention, adjusted_uc, PIN, Coverage, `Target Coverage`)
     
          
     lmic_df <- lmic_df %>% 
       rename("LMIC.Unit.Price" = adjusted_uc,
              "LMIC.PIN" = PIN,
              "LMIC.Coverage" = Coverage,
              "LMIC.Target" = `Target Coverage`)
     
     write.csv(lmic_df, "Unit_cost_LMIC_0422.csv")
     
```

# Merge into one & output
```{r}
df_all <- merge(lic_df, lmic_df[,c("Code","LMIC.Unit.Price", "LMIC.PIN","LMIC.Coverage", "LMIC.Target")], by = "Code")

write.csv(df_all, "df_all_0422.csv")
```

```{r}
# From Sarah
LIC_total_pop <- as.numeric(896507437.8)
LMIC_total_pop <- as.numeric(2671721030)
```


```{r}
df <- df.lic <- read.csv("Unit_cost_LIC_0422.csv")

# LIC
df$LIC.Unit.Price <- round(df$LIC.Unit.Price, 4)
df$LIC.Coverage <- round(df$LIC.Coverage, 4)


LIC_GNI_2015 <- as.numeric(GNI[GNI$Country == "LIC",]$X2015)
LMIC_GNI_2015 <- as.numeric(GNI[GNI$Country == "LMIC", c("2015")])


# All data: Revised formula
df <- df %>% 
  mutate(#LIC
         LIC_corrent_cost = LIC.Unit.Price*(1+0.5)*(1+0.17)*LIC.PIN*LIC.Coverage
         )

df$LIC_target_cost <- ifelse(df$LIC.Coverage >= df$LIC.Target, 
                         df$LIC.Unit.Price*(1+0.5)*(1+0.17)*df$LIC.PIN*df$LIC.Coverage,
                         df$LIC.Unit.Price*(1+0.5)*(1+0.17)*df$LIC.PIN*df$LIC.Target)

df$LIC_increment <-  df$LIC_target_cost - df$LIC_corrent_cost

write.csv(df, "df_all_re_0422_LIC.csv")



# LIC
df.sum.lic <- df %>% 
  #group_by(HPP) %>% 
  summarise(LIC_increment_sum = round(sum(LIC_increment, na.rm = T)/1000000000, 2),
            LIC_increment_per = round(sum(LIC_increment/LIC_total_pop, na.rm = T), 2),
            LIC_Total = round(sum(LIC_target_cost, na.rm = T)/1000000000, 2 ),
            LIC_Total_per = round(sum(LIC_target_cost, na.rm = T)/LIC_total_pop, 2 ),
            LIC_GNI_increment = round(((sum(LIC_increment, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2),
            LIC_GNI_total = round(((sum(LIC_target_cost, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2)
            )

df.sum.lic <- data.frame(t(df.sum.lic))



df.sum.lic.HPP <- df %>% 
  group_by(HPP) %>% 
  summarise(LIC_increment_sum = round(sum(LIC_increment, na.rm = T)/1000000000, 2),
            LIC_increment_per = round(sum(LIC_increment, na.rm = T)/LIC_total_pop, 2),
            LIC_Total = round(sum(LIC_target_cost, na.rm = T)/1000000000, 2),
            LIC_Total_per = round(sum(LIC_target_cost, na.rm = T)/LIC_total_pop, 2 ),
            LIC_GNI_increment = round(((sum(LIC_increment, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2),
            LIC_GNI_total = round(((sum(LIC_target_cost, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2)
            )
df.sum.lic.HPP <- df.sum.lic.HPP[2,-1]
df.sum.lic.HPP2 <- data.frame(t(df.sum.lic.HPP))
```

```{r}
df <- df.lmic <- read.csv("Unit_cost_LMIC_0422.csv")

df$LMIC.Coverage <- round(df$LMIC.Coverage, 4)
df$LMIC.Unit.Price <- round(df$LMIC.Unit.Price, 4)

# All data
df <- df %>% 
  mutate( #LMIC
         LMIC_corrent_cost = LMIC.Unit.Price*(1+0.5)*(1+0.17)*LMIC.PIN*LMIC.Coverage
         )

df$LMIC_target_cost <- ifelse(df$LMIC.Coverage >= df$LMIC.Target, 
                      df$LMIC.Unit.Price*(1+0.5)*(1+0.17)*df$LMIC.PIN*df$LMIC.Coverage,
                      df$LMIC.Unit.Price*(1+0.5)*(1+0.17)*df$LMIC.PIN*df$LMIC.Target)

df$LMIC_increment <-  df$LMIC_target_cost - df$LMIC_corrent_cost

write.csv(df, "df_all_re_0422_LMIC.csv")


# LMIC

df.sum.lmic <- df %>% 
  #group_by(HPP) %>% 
  summarise(LMIC_increment_sum = round(sum(LMIC_increment, na.rm = T)/1000000000,2),
            LMIC_increment_per = round(sum(LMIC_increment, na.rm = T)/LMIC_total_pop,2),
            LMIC_Total = round(sum(LMIC_target_cost, na.rm = T)/1000000000,2),
            LMIC_Total_per = round(sum(LMIC_target_cost, na.rm = T)/LMIC_total_pop,2),
            LMIC_GNI_increment = round(((sum(LMIC_increment, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2),
            LMIC_GNI_total = round(((sum(LMIC_target_cost, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2)
            )

df.sum.lmic <- data.frame(t(df.sum.lmic))



df.sum.lmic.HPP <- df %>% 
  group_by(HPP) %>% 
  summarise(LMIC_increment_sum = round(sum(LMIC_increment, na.rm = T)/1000000000,2),
            LMIC_increment_per = round(sum(LMIC_increment, na.rm = T)/LMIC_total_pop,2),
            LMIC_Total = round(sum(LMIC_target_cost, na.rm = T)/1000000000,2),
            LMIC_Total_per = round(sum(LMIC_target_cost, na.rm = T)/LMIC_total_pop,2),
            LMIC_GNI_increment = round(((sum(LMIC_increment, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2),
            LMIC_GNI_total = round(((sum(LMIC_target_cost, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2)
            )
df.sum.lmic.HPP <- df.sum.lmic.HPP[2,-1]
df.sum.lmic.HPP2 <- data.frame(t(df.sum.lmic.HPP))

result.df <- as.data.frame(cbind(df.sum.lic.HPP2, df.sum.lic, df.sum.lmic.HPP2, df.sum.lmic))

result.df <- result.df %>% 
  rename("LIC.HPP" = t.df.sum.lic.HPP. , "LIC.EUHC" = t.df.sum.lic. , "LMIC.HPP" = t.df.sum.lmic.HPP. , "LMIC.EUHC" = t.df.sum.lmic.)

rownames(result.df) <- c("Incremental annual cost (US$, billions)",
                         "Incremental annual cost per person (US$)",
                         "Total annual cost (US$, billions)",
                         "Total annual cost per person (US$)",
                         "Incremental annual cost as a share of 2015 GNI per person (%)",
                         "Total annual cost as a share of 2015 GNI per person (%)")

result.df

write.csv(result.df, "Result_0422.csv")
```

# PSA: probablistic piece = multipliers
```{r}
library(triangle)

set.seed(1234567)
# Random draw from the triangle distribution
psa_coverage <- rtriangle(n = 10000, a = -0.15, b = 0.15, c = 0)
psa_HF <- rtriangle(n = 10000, a = 30, b = 80, c = 50)
psa_aboce_HF <- rtriangle(n = 10000, a = 9, b = 27, c=17)
psa_UC <- rtriangle(n = 10000, a = 0.7, b = 1.3, c=1)
psa_PIN <- rtriangle(n = 10000, a = 0.9, b = 1.1, c=1)
psa_fertility_LIC <- rtriangle(n = 10000, a = 0.87, b = 1.13, c=1)
psa_fertility_LMIC <- rtriangle(n = 10000, a = 0.8, b = 1.2, c=1)

sensi_int_df <- as.data.frame(cbind(psa_coverage, psa_HF, psa_aboce_HF, psa_UC, psa_PIN, psa_fertility_LIC, psa_fertility_LMIC))

write.csv(sensi_int_df, "PSA_setting.csv")

par(mfrow=c(3,3))
hist(psa_HF)
hist(psa_aboce_HF)
hist(psa_coverage)
hist(psa_UC)
hist(psa_PIN)
hist(psa_fertility_LIC)
hist(psa_fertility_LMIC)

# Use PSA data to calculate the final figures
df <- read.csv("Unit_cost_LIC_all_0422.csv")

sample.df.sum.all <- data.frame(LIC_increment_sum = NA, LIC_increment_per = NA, LIC_Total = NA, LIC_Total_per = NA , LIC_GNI_increment = NA, LIC_GNI_total = NA)

sample.df.sum.all.HPP <- data.frame(LIC_increment_sum = NA, LIC_increment_per = NA, LIC_Total = NA, LIC_Total_per = NA , LIC_GNI_increment = NA, LIC_GNI_total = NA)

df.sum.platform <- data.frame(Platform = NA, increment_sum = NA, no = NA, group = NA)
df.sum.urgency <- data.frame(Urgency = NA, increment_sum = NA, no = NA, group = NA)

i <- 1

for (i in 1:10000){
  df$total_cost <- ifelse(df$Multipliers == "None",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN,
                          
                   ifelse(df$Multipliers == "Fertility",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN*sensi_int_df$psa_fertility_LIC[i],
                                   
                    ifelse(df$Multipliers == "Population",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN*sensi_int_df$psa_PIN[i],
                    ifelse(df$Multipliers == "Both",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN*sensi_int_df$psa_PIN[i]*sensi_int_df$psa_fertility_LIC[i],
                                                 NA))))
    
    # Current cost to achieve current baseline coverage

      df$current_cost <- ifelse(df$Multipliers == "None",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN,
                          
                   ifelse(df$Multipliers == "Fertility",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN*sensi_int_df$psa_fertility_LIC[i],
                                   
                    ifelse(df$Multipliers == "Population",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN*sensi_int_df$psa_PIN[i],
                    ifelse(df$Multipliers == "Both",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN*sensi_int_df$psa_PIN[i]*sensi_int_df$psa_fertility_LIC[i],
                                                 NA))))
      
      df$total_cost <-     ifelse(df$current_cost >= df$total_cost, 
                                  df$current_cost,
                                  df$total_cost)
      
      df$increment <- df$total_cost - df$current_cost
      
      sample.df_sum <- df %>% 
  #group_by(HPP) %>% 
  summarise(LIC_increment_sum = round(sum(increment, na.rm = T)/1000000000, 2),
            LIC_increment_per = round(sum(increment/LIC_total_pop, na.rm = T), 2),
            LIC_Total = round(sum(total_cost, na.rm = T)/1000000000, 2 ),
            LIC_Total_per = round(sum(total_cost, na.rm = T)/LIC_total_pop, 2 ),
            LIC_GNI_increment = round(((sum(increment, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2),
            LIC_GNI_total = round(((sum(total_cost, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2)
            )
  
  sample.df.sum.all <- rbind(sample.df.sum.all, sample.df_sum)
  
  # Develop a summary table for HPP
sample.df_sum.HPP <- df %>% 
  group_by(HPP) %>% 
  summarise(LIC_increment_sum = round(sum(increment, na.rm = T)/1000000000, 2),
            LIC_increment_per = round(sum(increment/LIC_total_pop, na.rm = T), 2),
            LIC_Total = round(sum(total_cost, na.rm = T)/1000000000, 2 ),
            LIC_Total_per = round(sum(total_cost, na.rm = T)/LIC_total_pop, 2 ),
            LIC_GNI_increment = round(((sum(increment, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2),
            LIC_GNI_total = round(((sum(total_cost, na.rm = T)/LIC_total_pop) / LIC_GNI_2015)*100,2)
            )
sample.df_sum.HPP <- sample.df_sum.HPP[2,-1]
sample.df.sum.all.HPP <- rbind(sample.df.sum.all.HPP, sample.df_sum.HPP)


  #Platform
   sum.platform <- df %>% 
     group_by(Platform) %>% 
     summarize(increment_sum = (sum(increment, na.rm = T)/1000000000))
   
   sum.platform$no <- i
   sum.platform$group <- "LIC"
   df.sum.platform <- rbind(df.sum.platform, sum.platform)
   
#Urgency
     sum.urgency <- df %>% 
     group_by(Urgency) %>% 
     summarize(increment_sum = (sum(increment, na.rm = T)/1000000000))
   
   sum.urgency$no <- i
   sum.urgency$group <- "LIC"
   df.sum.urgency <- rbind(df.sum.urgency, sum.urgency)

}

sample.df.sum.all.HPP.LIC <- sample.df.sum.all.HPP[-1,]
sample.df.sum.all.LIC <- sample.df.sum.all[-1,]
df.sum.platform.LIC <- df.sum.platform[-1,]
df.sum.urgency.LIC <- df.sum.urgency[-1,]

```

```{r}
# Use PSA data to calculate the final figures
df <- read.csv("Unit_cost_LMIC_all_0422.csv")

sample.df.sum.all <- data.frame(LMIC_increment_sum = NA, LMIC_increment_per = NA, LMIC_Total = NA, LMIC_Total_per = NA , LMIC_GNI_increment = NA, LMIC_GNI_total = NA)

sample.df.sum.all.HPP <- data.frame(LMIC_increment_sum = NA, LMIC_increment_per = NA, LMIC_Total = NA, LMIC_Total_per = NA , LMIC_GNI_increment = NA, LMIC_GNI_total = NA)

df.sum.platform <- data.frame(Platform = NA, increment_sum = NA, no = NA, group = NA)
df.sum.urgency <- data.frame(Urgency = NA, increment_sum = NA, no = NA, group = NA)


for (i in 1:10000){
  df$total_cost <- ifelse(df$Multipliers == "None",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN,
                          
                   ifelse(df$Multipliers == "Fertility",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN*sensi_int_df$psa_fertility_LIC[i],
                                   
                    ifelse(df$Multipliers == "Population",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN*sensi_int_df$psa_PIN[i],
                    ifelse(df$Multipliers == "Both",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (0.8)*
                            df$PIN*sensi_int_df$psa_PIN[i]*sensi_int_df$psa_fertility_LIC[i],
                                                 NA))))
    
    # Current cost to achieve current baseline coverage

      df$current_cost <- ifelse(df$Multipliers == "None",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN,
                          
                   ifelse(df$Multipliers == "Fertility",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN*sensi_int_df$psa_fertility_LIC[i],
                                   
                    ifelse(df$Multipliers == "Population",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN*sensi_int_df$psa_PIN[i],
                    ifelse(df$Multipliers == "Both",
                            (df$adjusted_uc*sensi_int_df$psa_UC[i])*
                            (1+(sensi_int_df$psa_HF[i]/100))*
                            (1+(sensi_int_df$psa_aboce_HF[i]/100))*
                            (df$Coverage + sensi_int_df$psa_coverage[i])*
                            df$PIN*sensi_int_df$psa_PIN[i]*sensi_int_df$psa_fertility_LIC[i],
                                                 NA))))
      
            df$total_cost <-     ifelse(df$current_cost >= df$total_cost, 
                                  df$current_cost,
                                  df$total_cost)
      
      df$increment <- df$total_cost - df$current_cost
      
      
      sample.df_sum <- df %>% 
  #group_by(HPP) %>% 
  summarise(LMIC_increment_sum = round(sum(increment, na.rm = T)/1000000000, 2),
            LMIC_increment_per = round(sum(increment/LMIC_total_pop, na.rm = T), 2),
            LMIC_Total = round(sum(total_cost, na.rm = T)/1000000000, 2 ),
            LMIC_Total_per = round(sum(total_cost, na.rm = T)/LMIC_total_pop, 2 ),
            LMIC_GNI_increment = round(((sum(increment, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2),
            LMIC_GNI_total = round(((sum(total_cost, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2)
            )
  
  sample.df.sum.all <- rbind(sample.df.sum.all, sample.df_sum)
  
  # Develop a summary table for HPP
sample.df_sum.HPP <- df %>% 
  group_by(HPP) %>% 
  summarise(LMIC_increment_sum = round(sum(increment, na.rm = T)/1000000000, 2),
            LMIC_increment_per = round(sum(increment/LMIC_total_pop, na.rm = T), 2),
            LMIC_Total = round(sum(total_cost, na.rm = T)/1000000000, 2 ),
            LMIC_Total_per = round(sum(total_cost, na.rm = T)/LMIC_total_pop, 2 ),
            LMIC_GNI_increment = round(((sum(increment, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2),
            LMIC_GNI_total = round(((sum(total_cost, na.rm = T)/LMIC_total_pop) / LMIC_GNI_2015)*100,2)
            )
sample.df_sum.HPP <- sample.df_sum.HPP[2,-1]

  sample.df.sum.all.HPP <- rbind(sample.df.sum.all.HPP, sample.df_sum.HPP)
  
  #Platform
     sum.platform <- df %>% 
     group_by(Platform) %>% 
     summarize(increment_sum = (sum(increment, na.rm = T)/1000000000))
   
   sum.platform$no <- i
   sum.platform$group <- "LMIC"
   df.sum.platform <- rbind(df.sum.platform, sum.platform)
   
   #Urgency
     sum.urgency <- df %>% 
     group_by(Urgency) %>% 
     summarize(increment_sum = (sum(increment, na.rm = T)/1000000000))
   
   sum.urgency$no <- i
   sum.urgency$group <- "LMIC"
   df.sum.urgency <- rbind(df.sum.urgency, sum.urgency)
   
}

sample.df.sum.all.HPP.LMIC <- sample.df.sum.all.HPP[-1,]
sample.df.sum.all.LMIC <- sample.df.sum.all[-1,]
df.sum.platform.LMIC <- df.sum.platform[-1,]
df.sum.urgency.LMIC <- df.sum.urgency[-1,]


```

# PSA result
```{r}
PSA_result <- data.frame(LIC.HPP = NA, LIC.EUHC = NA, LMIC.HPP = NA, LMIC.EUHC = NA)

 for(i in 1:6){
   PSA_result[i,1] <- paste(as.character(quantile(sample.df.sum.all.HPP.LIC[-1,i],c(0.025)))," - ", as.character(quantile(sample.df.sum.all.HPP.LIC[-1,i],c(0.975))))
 }

 for(i in 1:6){
   PSA_result[i,2] <- paste(as.character(quantile(sample.df.sum.all.LIC[-1,i],c(0.025)))," - ", as.character(quantile(sample.df.sum.all.LIC[-1,i],c(0.975))))
 }

 for(i in 1:6){
   PSA_result[i,3] <- paste(as.character(quantile(sample.df.sum.all.HPP.LMIC[-1,i],c(0.025)))," - ", as.character(quantile(sample.df.sum.all.HPP.LMIC[-1,i],c(0.975))))
 }

 for(i in 1:6){
   PSA_result[i,4] <- paste(as.character(quantile(sample.df.sum.all.LMIC[-1,i],c(0.025)))," - ", as.character(quantile(sample.df.sum.all.LMIC[-1,i],c(0.975))))
 }
 
 
 PSA_result$Indicators <- c("Incremental annual cost (US$, billions)",
                         "Incremental annual cost per person (US$)",
                         "Total annual cost (US$, billions)",
                         "Total annual cost per person (US$)",
                         "Incremental annual cost as a share of 2015 GNI per person (%)",
                         "Total annual cost as a share of 2015 GNI per person (%)")
 
 
 PSA_result <- PSA_result %>% 
   select(Indicators, LIC.HPP, LIC.EUHC, LMIC.HPP, LMIC.EUHC)
 
 write.csv(PSA_result, "PSA_result_0422.csv")
```

# PSA by platform

```{r}
df.sum.platform.both <- rbind(df.sum.platform.LIC,df.sum.platform.LMIC)

df.sum.platform.total <- df.sum.platform.both %>% 
  group_by(no) %>%
  summarize(increment_total = (sum(increment_sum, na.rm = T)))

df.sum.platform.subtotal <- df.sum.platform.both %>% 
  group_by(no, Platform) %>%
  summarize(increment_total = (sum(increment_sum, na.rm = T)))


df.sum.platform.subtotal$total_cost <- NA
for (i in 1:10000){
  df.sum.platform.subtotal[df.sum.platform.subtotal$no == i,]$total_cost <-  as.numeric(df.sum.platform.total %>% filter(no == i) %>% select(increment_total))
}

# Share
df.sum.platform.subtotal$share <- df.sum.platform.subtotal$increment_total / df.sum.platform.subtotal$total_cost

# Percentage
PSA_result_Platform <- data.frame(Platform = NA, Crls = NA)

category <- c("Population based", "Community", "Health center", "First-level hospital", "Referral and speacialty hospitals")


for(i in 1:5) {
  PSA_result_Platform[i,]$Platform <- category[i]
  PSA_result_Platform[i,]$Crls <- paste(as.character(quantile(df.sum.platform.subtotal[df.sum.platform.subtotal$Platform == category[i],]$share,c(0.025)))," - ", as.character(quantile(df.sum.platform.subtotal[df.sum.platform.subtotal$Platform == category[i],]$share,c(0.975)))
                                    )
}


 write.csv(PSA_result_Platform, "PSA_result_platform_0422.csv")

```

# PSA by Urgency
```{r}
df.sum.urgency.both <- rbind(df.sum.urgency.LIC,df.sum.urgency.LMIC)

df.sum.urgency.total <- df.sum.urgency.both %>% 
  group_by(no) %>%
  summarize(increment_total = (sum(increment_sum, na.rm = T)))

df.sum.urgency.subtotal <- df.sum.urgency.both %>% 
  group_by(no, Urgency) %>%
  summarize(increment_total = (sum(increment_sum, na.rm = T)))


df.sum.urgency.subtotal$total_cost <- NA
for (i in 1:10000){
  df.sum.urgency.subtotal[df.sum.urgency.subtotal$no == i,]$total_cost <-  as.numeric(df.sum.urgency.total %>% filter(no == i) %>% select(increment_total))
}

# Share
df.sum.urgency.subtotal$share <- df.sum.urgency.subtotal$increment_total / df.sum.urgency.subtotal$total_cost

# Percentage
PSA_result_Urgency <- data.frame(Urgency = NA, Crls = NA)

category <- c("Urgent", "Chronic", "Time-bound (non-urgent)")

for(i in 1:3) {
  PSA_result_Urgency[i,]$Urgency <- category[i]
  PSA_result_Urgency[i,]$Crls <- paste(as.character(quantile(df.sum.urgency.subtotal[df.sum.urgency.subtotal$Urgency == category[i],]$share,c(0.025)))," - ", as.character(quantile(df.sum.urgency.subtotal[df.sum.urgency.subtotal$Urgency == category[i],]$share,c(0.975)))
                                    )
}


 write.csv(PSA_result_Urgency, "PSA_result_urgency_0422.csv")
```

